const UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1';
const DISNEY='ZGlzbmV5JmJyb3dzZXImMS4wLjA.Cu56AgSfBTDag5NiRA81oLHkDZfu5L3CKadnefEAY84';
const S={ok:['✅','解锁','#34C759'],partial:['⚠️','部分','#FF9F0A'],blocked:['❌','不可用','#FF453A'],error:['❓','失败','#8E8E93']};
const N=['Netflix','Disney+','YouTube Premium','Prime Video','Spotify','Max','Paramount+','Peacock','BBC iPlayer','Abema','Bahamut Anime','KKTV'];
function env(c,k,d=''){return String(c.env?.[k]??d).trim()}
function opt(c,x={}){const o={...x,headers:{...(x.headers||{})}},p=env(c,'POLICY'),t=parseInt(env(c,'TIMEOUT','8000'));if(p)o.policy=p;o.timeout=o.timeout||(!isNaN(t)?t:8000);return o}
function out(name,status,detail='',region=''){return{name,status,detail,region}}
async function txt(r){try{return await r.text()}catch{return''}}
function find(o,k){if(!o||typeof o!=='object')return; if(Object.prototype.hasOwnProperty.call(o,k))return o[k];for(const v of Object.values(o)){const x=find(v,k);if(x!==undefined)return x}}
async function get(c,u,x={}){return c.http.get(u,opt(c,{headers:{'User-Agent':UA,...(x.headers||{})},credentials:'omit',...x}))}
async function post(c,u,x={}){return c.http.post(u,opt(c,{headers:{'User-Agent':UA,...(x.headers||{})},credentials:'omit',...x}))}
async function trace(c){try{const r=await get(c,'https://1.1.1.1/cdn-cgi/trace'),t=await txt(r),d={};t.split('\n').forEach(l=>{const i=l.indexOf('=');if(i>0)d[l.slice(0,i)]=l.slice(i+1).trim()});return{ip:d.ip||'Unknown',region:d.loc||'Unknown'}}catch{return{ip:'Unknown',region:'Unknown'}}}
async function netflix(c,fb){try{const ids=['81280792','70143836'],a=await Promise.all(ids.map(async id=>{const r=await get(c,`https://www.netflix.com/title/${id}`,{redirect:'follow','headers':{'Accept-Language':'en-US,en;q=.9'}});const t=await txt(r);return{r,t,b:r.status===403||r.status===404||/Oh no!|not available in your (?:country|region)|unavailable/i.test(t)}}));const all=a.map(x=>x.t).join('\n'),m=all.match(/"countryCode":"([A-Z]{2})"/)||all.match(/"id":"([A-Z]{2})"[^\n]{0,200}?"countryName"/),reg=m?.[1]||fb;if(a.every(x=>x.b))return out('Netflix','partial','仅自制剧 / 受限',reg);if(a.some(x=>x.r.status<400&&!x.b))return out('Netflix','ok','完整解锁',reg);return out('Netflix','blocked','测试片源不可用',reg)}catch{return out('Netflix','error','请求失败')}}
async function disney(c){try{const h={'authorization':`Bearer ${DISNEY}`,'content-type':'application/json; charset=UTF-8'};let r=await post(c,'https://disney.api.edge.bamgrid.com/devices',{headers:h,body:JSON.stringify({deviceFamily:'browser',applicationRuntime:'chrome',deviceProfile:'windows',attributes:{}})}),t=await txt(r);if(r.status===403)return out('Disney+','blocked','IP 被拒绝');let j={};try{j=JSON.parse(t)}catch{}const a=find(j,'assertion')||(t.match(/"assertion"\s*:\s*"([^"]+)"/)||[])[1];if(!a)return out('Disney+','error','无设备令牌');const b=`grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&latitude=0&longitude=0&platform=browser&subject_token=${encodeURIComponent(a)}&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Adevice`;r=await post(c,'https://disney.api.edge.bamgrid.com/token',{headers:{authorization:`Bearer ${DISNEY}`,'content-type':'application/x-www-form-urlencoded'},body:b});t=await txt(r);if(r.status===403||/forbidden-location/i.test(t))return out('Disney+','blocked','地区不可用');try{j=JSON.parse(t)}catch{j={}}const rt=find(j,'refresh_token');if(!rt)return out('Disney+','error','无刷新令牌');r=await post(c,'https://disney.api.edge.bamgrid.com/graph/v1/device/graphql',{headers:{authorization:DISNEY,'content-type':'application/json'},body:JSON.stringify({query:'mutation refreshToken($input: RefreshTokenInput!) { refreshToken(refreshToken: $input) { activeSession { sessionId } } }',variables:{input:{refreshToken:rt}}})});t=await txt(r);try{j=JSON.parse(t)}catch{j={}}const reg=find(j,'countryCode')||(t.match(/"countryCode"\s*:\s*"([A-Z]{2})"/)||[])[1]||'',ok=find(j,'inSupportedLocation');if(ok===true||ok==='true'||reg==='JP')return out('Disney+','ok','可用',reg);if(reg)return out('Disney+','partial','地区已识别',reg);return out('Disney+','error','无法识别地区')}catch{return out('Disney+','error','请求失败')}}
async function youtube(c){try{const r=await get(c,'https://www.youtube.com/premium',{redirect:'follow',headers:{'Accept-Language':'en-US,en;q=.9'}}),t=await txt(r),reg=(t.match(/"INNERTUBE_CONTEXT_GL"\s*:\s*"([A-Z]{2})"/)||[])[1]||'';if(/google\.cn|Premium is not available in your country/i.test(t))return out('YouTube Premium','blocked','Premium 不可用',reg||'CN');if(r.status===200&&/YouTube Premium|ad-free/i.test(t))return out('YouTube Premium','ok','可订阅',reg);return out('YouTube Premium','error',`页面异常 ${r.status}`,reg)}catch{return out('YouTube Premium','error','请求失败')}}
async function prime(c){try{const r=await get(c,'https://www.primevideo.com/',{redirect:'follow'}),t=await txt(r),reg=(t.match(/"currentTerritory"\s*:\s*"([A-Z]{2,3})"/)||[])[1]||'';if(/"isServiceRestricted"\s*:\s*true|not available in your location/i.test(t))return out('Prime Video','blocked','地区限制',reg);return reg?out('Prime Video','ok','可用',reg):out('Prime Video','error','无法识别地区')}catch{return out('Prime Video','error','请求失败')}}
async function spotify(c){try{const b='birth_day=11&birth_month=11&birth_year=2000&collect_personal_info=undefined&displayname=EgernCheck&gender=male&iagree=1&key=a1e486e2729f46d6bb368d6b2bcda326&platform=www&send-email=0&thirdpartyemail=0',r=await post(c,'https://spclient.wg.spotify.com/signup/public/v1/account',{headers:{'content-type':'application/x-www-form-urlencoded','Accept-Language':'en'},body:b}),t=await txt(r);let j={};try{j=JSON.parse(t)}catch{}const reg=j.country||(t.match(/"country"\s*:\s*"([A-Z]{2})"/)||[])[1]||'';if(j.is_country_launched===false)return out('Spotify','blocked','未开放',reg);return reg?out('Spotify','ok','可用',reg):out('Spotify','error','无法识别地区')}catch{return out('Spotify','error','请求失败')}}
async function max(c){try{const r=await get(c,'https://www.max.com/',{redirect:'follow'}),t=await txt(r),reg=(t.match(/"countryCode"\s*:\s*"([A-Z]{2})"/)||t.match(/countryCode%22%3A%22([A-Z]{2})/i)||[])[1]||'';if(/not available in your region|unavailable in your country/i.test(t))return out('Max','blocked','地区不可用',reg);return reg?out('Max','ok','可用',reg):r.status===200?out('Max','partial','页面可访问'):out('Max','error',`HTTP ${r.status}`)}catch{return out('Max','error','请求失败')}}
async function redirects(c,u){for(let i=0;i<6;i++){const r=await get(c,u,{redirect:'manual'});if(![301,302,303,307,308].includes(r.status))return[r,u];const l=r.headers?.get?.('location');if(!l)return[r,u];u=new URL(l,u).href}throw Error('redirect')}
async function paramount(c){try{const[r,u]=await redirects(c,'https://www.paramountplus.com/'),p=new URL(u),x=p.pathname.split('/').filter(Boolean)[0]||'',reg=x.length<=3?x.toUpperCase():'US';if(reg==='INTL'||/\/intl(?:\/|$)/i.test(p.pathname))return out('Paramount+','blocked','当前地区不可用');return r.status<400?out('Paramount+','ok','可用',reg):out('Paramount+','error',`HTTP ${r.status}`,reg)}catch{return out('Paramount+','error','请求失败')}}
async function peacock(c){try{const[r,u]=await redirects(c,'https://www.peacocktv.com/'),t=await txt(r);if(/unavailable|not-available/i.test(u)||/not available in your (country|region)/i.test(t))return out('Peacock','blocked','仅美国可用');return r.status===200?out('Peacock','ok','可用','US'):out('Peacock','error',`HTTP ${r.status}`)}catch{return out('Peacock','error','请求失败')}}
async function bbc(c){try{const r=await get(c,'https://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/pc/vpid/bbc_one_london/format/json/jsfunc/JS_callbacks0'),t=await txt(r);if(/geolocation/i.test(t))return out('BBC iPlayer','blocked','仅英国可用');if(/vs-hls-push-uk/i.test(t))return out('BBC iPlayer','ok','可播放','GB');return out('BBC iPlayer','error',`接口异常 ${r.status}`)}catch{return out('BBC iPlayer','error','请求失败')}}
async function abema(c){try{const r=await get(c,'https://api.abema.io/v1/ip/check?device=android'),t=await txt(r),reg=(t.match(/"isoCountryCode"\s*:\s*"([A-Z]{2})"/)||[])[1]||'';return reg==='JP'?out('Abema','ok','日本完整内容','JP'):reg?out('Abema','partial','仅海外内容',reg):out('Abema','blocked','不可用')}catch{return out('Abema','error','请求失败')}}
async function bahamut(c){try{let r=await get(c,'https://ani.gamer.com.tw/ajax/getdeviceid.php',{credentials:'include'}),t=await txt(r),j={};try{j=JSON.parse(t)}catch{}const d=j.deviceid||(t.match(/"deviceid"\s*:\s*"([^"]+)"/)||[])[1];if(!d)return out('Bahamut Anime','error','无 device id');r=await get(c,`https://ani.gamer.com.tw/ajax/token.php?adID=89422&sn=37783&device=${encodeURIComponent(d)}`,{credentials:'include'});t=await txt(r);return /animeSn/i.test(t)?out('Bahamut Anime','ok','可播放','TW'):out('Bahamut Anime','blocked','动画疯地区限制')}catch{return out('Bahamut Anime','error','请求失败')}}
async function kktv(c){try{const r=await get(c,'https://api.kktv.me/v3/ipcheck'),t=await txt(r),reg=(t.match(/"country"\s*:\s*"([A-Z]{2})"/)||[])[1]||'';return reg==='TW'?out('KKTV','ok','台湾区可用','TW'):reg?out('KKTV','blocked','仅台湾可用',reg):out('KKTV','error',`接口异常 ${r.status}`)}catch{return out('KKTV','error','请求失败')}}
function row(x,small=false){const s=S[x.status]||S.error,d=[x.detail,x.region?`(${x.region})`:''].filter(Boolean).join(' ');return{type:'stack',direction:'row',alignItems:'center',gap:5,children:[{type:'text',text:s[0],font:{size:small?10:12}},{type:'text',text:x.name,font:{size:small?10:12,weight:'semibold'},textColor:'#FFFFFF',flex:1,maxLines:1,minScale:.6},{type:'text',text:d||s[1],font:{size:small?9:11,weight:'medium'},textColor:s[2],textAlign:'right',flex:1,maxLines:1,minScale:.5}]}}
function widget(c,net,a){const f=c.widgetFamily||'systemLarge',n=a.reduce((z,x)=>(z[x.status]=(z[x.status]||0)+1,z),{}),sum=`✅ ${n.ok||0}  ⚠️ ${n.partial||0}  ❌ ${n.blocked||0}  ❓ ${n.error||0}`;if(f==='accessoryInline')return{type:'widget',children:[{type:'text',text:`流媒体 ${sum}`}]};if(f==='accessoryCircular')return{type:'widget',children:[{type:'text',text:`${n.ok||0}/${a.length}`,font:{size:'headline',weight:'bold'}}]};if(f==='accessoryRectangular')return{type:'widget',children:[{type:'text',text:`流媒体 · ${net.region}`,font:{size:'headline',weight:'semibold'}},{type:'text',text:sum,font:{size:'caption1'}}]};const m=f==='systemSmall'?4:f==='systemMedium'?6:a.length,ch=[{type:'stack',direction:'row',children:[{type:'text',text:'流媒体解锁',font:{size:'headline',weight:'bold'},textColor:'#FFFFFF',flex:1},{type:'text',text:net.region,font:{size:'caption1',weight:'semibold'},textColor:'#64D2FF'}]},{type:'stack',direction:'row',children:[{type:'text',text:net.ip,font:{size:'caption2',family:'Menlo'},textColor:'#A1A1AA',flex:1,maxLines:1,minScale:.55},{type:'text',text:sum,font:{size:'caption2'},textColor:'#D1D1D6'}]},...a.slice(0,m).map(x=>row(x,f!=='systemLarge'&&f!=='systemExtraLarge'))];return{type:'widget',refreshAfter:new Date(Date.now()+1800000).toISOString(),backgroundGradient:{type:'linear',colors:['#0B1020','#111827','#0F172A'],startPoint:{x:0,y:0},endPoint:{x:1,y:1}},padding:f==='systemSmall'?12:14,gap:5,children:ch}}
export default async function(ctx){const net=await trace(ctx),jobs=[netflix(ctx,net.region),disney(ctx),youtube(ctx),prime(ctx),spotify(ctx),max(ctx),paramount(ctx),peacock(ctx),bbc(ctx),abema(ctx),bahamut(ctx),kktv(ctx)],r=await Promise.allSettled(jobs),a=r.map((x,i)=>x.status==='fulfilled'?x.value:out(N[i],'error','脚本异常'));if(!ctx.widgetFamily&&ctx.notify){ctx.notify({title:'Egern 流媒体解锁查询',body:[`出口: ${net.ip} · ${net.region}`,...a.map(x=>`${S[x.status][0]} ${x.name}: ${x.detail}${x.region?` (${x.region})`:''}`)].join('\n')})}return widget(ctx,net,a)}
